export enum BookingStatus {
  PENDING_CONFIRMATION = "PENDING_CONFIRMATION",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  CONFIRMED_PAID = "CONFIRMED_PAID",
  CANCELLED_BY_CUSTOMER = "CANCELLED_BY_CUSTOMER",
  CANCELLED_BY_COMPANY = "CANCELLED_BY_COMPANY",
  COMPLETED = "COMPLETED",
  NO_SHOW = "NO_SHOW"
}

export enum CompanyServicesLocation {
  PHYSICAL_LOCATION = "PHYSICAL_LOCATION",
  AT_CLIENT_LOCATION = "AT_CLIENT_LOCATION",
  DIGITAL = "DIGITAL"
}

export enum CompanySize {
  2_5 = "2_5",
  6_10 = "6_10",
  +11 = "+11"
}

export enum CompanySpecialisation {
  HAIR_SALON = "HAIR_SALON",
  NAILS = "NAILS",
  EYEBROWS_AND_LASHES = "EYEBROWS_AND_LASHES",
  BEAUTY_SALON = "BEAUTY_SALON",
  MEDICAL_SPA = "MEDICAL_SPA",
  BARBER = "BARBER",
  MASSAGE = "MASSAGE",
  SPA_AND_SAUNA = "SPA_AND_SAUNA",
  WAXING_SALON = "WAXING_SALON",
  TATTOO_AND_PIERCING = "TATTOO_AND_PIERCING",
  TANNING_STUDIO = "TANNING_STUDIO",
  FITNESS_AND_WELLNESS = "FITNESS_AND_WELLNESS",
  PHYSICAL_THERAPY = "PHYSICAL_THERAPY",
  HEALTH_PRACTICE = "HEALTH_PRACTICE",
  PET_GROOMING = "PET_GROOMING",
  OTHER = "OTHER"
}

export enum CompanyType {
  BUSINESS = "BUSINESS",
  INDIVIDUAL = "INDIVIDUAL"
}

export enum UserType {
  COMPANY_ADMIN = "COMPANY_ADMIN",
  COMPANY_EMPLOYEE = "COMPANY_EMPLOYEE",
  CUSTOMER = "CUSTOMER"
}